### ISSUE TITLE
Question: What happens when there are no location listeners?

### ISSUE THREAD

**Issue by nevi-me** [patloew/RxLocation#1]
Hey, found this lib in Android Arsenal. I recently started migrating to RxJava 2, and I'm trying to simplify some of my code.

I use Activity Recognition, Location and Geofencing, so I'm keen on trying RxLocation out. I've been managing location myself using PublishSubjects and Broadcasters.

What I wanted to ask is: you suggest creating a single instance of RxLocation and sharing it, but what happens when I subscribe to location updates in one Activity, and then dispose my subscription? Does RxLocation stop listening to location changes until there's another subscription?

**Comment by patloew** [comment]
The `RxLocation` class is just a factory for the reactive types, so there is no need to create more than one instance in your app. You do not necessarily need to share the Singles, Flowables, … returned by the factory, however. Each call creates a new instance.

Yes, the `Observable<Location>` returned by `rxLocation.location().updates(locationRequest)` removes the listener when you dispose of the `Disposable` returned by your call to `subscribe()`. However, each subscription is handled separately. If you dispose of one subscription, and another subscription is still active, it will continue to listen for location changes (which means that it's also important to dispose of all your subscriptions when you don't need them anymore). Also, you can just get a new `Observable<Location>` from the factory later, if you need listen to location updates again in another component.

For background updates, you still need to register for updates with a `PendingIntent` via `rxLocation.location().requestUpdates(locationRequest, pendingIntent)`.
