### ISSUE TITLE
Did not  call setAlwaysShow(true) 

### ISSUE THREAD

**Issue by TonyTangAndroid** [patloew/RxLocation#11]
`getLocationSettingsRequestBuilder().addLocationRequest(locationRequest).build(), null, null);
`								
After location request is added, `setAlwaysShow(true) ` was not called, which will cause the following problem. [http://stackoverflow.com/questions/29824408/google-play-services-locationservices-api-new-option-never](http://stackoverflow.com/questions/29824408/google-play-services-locationservices-api-new-option-never)

**Comment by patloew** [comment]
There is a `check(LocationSettingsRequest)` and `checkAndHandleResolution(LocationSettingsRequest)`. There you can provide your own request which has `setAlwaysShow(true)`.

**Comment by TonyTangAndroid** [comment]
Awesome!
