### ISSUE TITLE
Proguard issue

### ISSUE THREAD

**Issue by TonyTangAndroid** [patloew/RxLocation#12]
The following issue will be met when the proguard is turned on.

`Warning:com.patloew.rxlocation.Geocoder: can't find referenced class com.patloew.rxlocation.Geocoder$$Lambda$1
Warning:com.patloew.rxlocation.Geocoder: can't find referenced class com.patloew.rxlocation.Geocoder$$Lambda$2
Warning:com.patloew.rxlocation.Geocoder: can't find referenced class com.patloew.rxlocation.Geocoder$$Lambda$3
Warning:com.patloew.rxlocation.Geocoder: can't find referenced class com.patloew.rxlocation.Geocoder$$Lambda$4`

**Comment by TonyTangAndroid** [comment]
Add the following two line into pro-guard file works good.

_-keep class com.patloew.rxlocation.** { *; }
 -dontwarn com.patloew.rxlocation.**_

**Comment by patloew** [comment]
Please update to version 1.0.1. Then you should not need any additional rules. See #7 and #8.
