### ISSUE TITLE
NO location info

### ISSUE THREAD

**Issue by chowaikong** [patloew/RxLocation#2]
I have downloaded and run your sample, but it shows last update never, current location and current address are not available, I look into your code but find no problem, any help?

**Comment by patloew** [comment]
Do you have Google Play Services installed on your phone (the latest version)? Please post error logs, if any.

I also just committed an update to the sample app, which checks for play services availability.

**Comment by vdubedout** [comment]
Same problem, I was using this as LocationRequest and nothing was coming out

```
locationRequest = LocationRequest.create()
        .setNumUpdates(1)
        .setPriority(LocationRequest.PRIORITY_BALANCED_POWER_ACCURACY)
        .setExpirationDuration(5000);
```

I removed the line ExpirationDuration and put a timeout in the `rxLocation.location().updates(locationRequest, 5, TimeUnit.SECONDS);` and it worked

**Comment by patloew** [comment]
@vdubedout I think this might be a different issue. E.g., there could have been no location available the first time, within 5 seconds. Or, you set the expiration duration and did not immediately make the call to request location updates. See the docs for [`setExpirationDuration()`](https://developers.google.com/android/reference/com/google/android/gms/location/LocationRequest.html#setExpirationDuration%28long%29).

Also, the timeout you pass to `rxLocation.location().updates()` is only the timeout for the call to `FusedLocationProviderApi.requestLocationUpdates()`. It does not time out, if no location is available after 5 seconds. I may have to clarify this part in the readme.

**Comment by chowaikong** [comment]
Alright, I think it's my network problem, thanks for the hints.
