### ISSUE TITLE
GoogleApiClient is not configured to use ActivityRecognition.API required for this call.

### ISSUE THREAD

**Issue by diogojg** [patloew/RxLocation#24]
It is not possible to use RxLocation.activity(). 
java.lang.IllegalArgumentException: GoogleApiClient is not configured to use ActivityRecognition.API required for this call.

My guess is that the statement of ".addApi(ActivityRecognition.API)" is missing from apiClient initialization.

mApiClient = new GoogleApiClient.Builder(this)
            .addApi(ActivityRecognition.API)
            .addConnectionCallbacks(this)
            .addOnConnectionFailedListener(this)
            .build();

**Comment by patloew** [comment]
Thanks for reporting the issue. This should be fixed in 1.0.2 :)
