### ISSUE TITLE
GPS turn on or off broadcast receiver

### ISSUE THREAD

**Issue by TonyTangAndroid** [patloew/RxLocation#29]
Currently, if we turn off the location and install the app, it will indeed pop up the dialog for user to turn on the location. But if the user refuses to turn on, there will be no further actions. So far, everything is expected.

Then if the user pulls down the notification center and turns on the GPS, the app will not respond to the change of GPS status until the app goes background and comes to foreground again.

I think it will be better experience for the app to respond the of GPS status change and start the update of location information directly. 

In this case, the library RxLocation could be considered as the solely source of location information update and remove all unnecessary code in app level. This should be achievable by registering GPS status change broadcast receiver in AndroidManifest.xml.

Just my two cents of thought.

**Comment by prangenberg** [comment]
+1 would be helpfull for me too

**Comment by patloew** [comment]
This library is now deprecated and not maintained anymore. Please switch to the [CoLocation library](https://github.com/patloew/CoLocation).
