### ISSUE TITLE
Potential memory leak detected by leak canary.

### ISSUE THREAD

**Issue by carlemil** [patloew/RxLocation#3]
In com.company.app:1.0:1.
* com.company.app.register.RegisterActivity has leaked:
* GC ROOT com.google.android.gms.location.internal.zzk$zzc.akX
* references com.google.android.gms.location.internal.zzk$zzb.akZ
* references pl.charmas.android.reactivelocation.observables.location.LocationUpdatesObservable$1.this$0 (anonymous implementation of com.google.android.gms.location.LocationListener)
* references pl.charmas.android.reactivelocation.observables.location.LocationUpdatesObservable.ctx
* leaks com.company.app.register.RegisterActivity instance
* Retaining: 408 KB.
* Reference Key: 80c14fda-cd48-4608-9b53-1a6bdb12d70f
* Device: LGE google Nexus 5 hammerhead
* Android Version: 6.0.1 API: 23 LeakCanary: 1.5 00f37f5
* Durations: watch=5010ms, gc=131ms, heap dump=5773ms, analysis=43370ms

* Details:
* Instance of com.google.android.gms.location.internal.zzk$zzc
|   akX = com.google.android.gms.location.internal.zzk$zzb@317852800 (0x12f20c80)
|   mDescriptor = java.lang.String@315218560 (0x12c9da80)
|   mObject = -1608538680
|   mOwner = com.google.android.gms.location.internal.zzk$zzc@317852704 (0x12f20c20)
|   shadow$_klass_ = com.google.android.gms.location.internal.zzk$zzc
|   shadow$_monitor_ = 0
* Instance of com.google.android.gms.location.internal.zzk$zzb
|   akZ = pl.charmas.android.reactivelocation.observables.location.LocationUpdatesObservable$1@317862016 (0x12f23080)
|   mAsynchronous = false
|   mCallback = null
|   mLooper = android.os.Looper@316507008 (0x12dd8380)
|   mMessenger = null
|   mQueue = android.os.MessageQueue@316518464 (0x12ddb040)
|   shadow$_klass_ = com.google.android.gms.location.internal.zzk$zzb
|   shadow$_monitor_ = 0
* Instance of pl.charmas.android.reactivelocation.observables.location.LocationUpdatesObservable$1
|   this$0 = pl.charmas.android.reactivelocation.observables.location.LocationUpdatesObservable@321692928 (0x132ca500)
|   val$observer = rx.observers.SafeSubscriber@316969072 (0x12e49070)
|   shadow$_klass_ = pl.charmas.android.reactivelocation.observables.location.LocationUpdatesObservable$1
|   shadow$_monitor_ = -2122113462
* Instance of pl.charmas.android.reactivelocation.observables.location.LocationUpdatesObservable
|   static $staticOverhead = byte[8]@317531105 (0x12ed23e1)
|   static TAG = java.lang.String@315222064 (0x12c9e830)
|   listener = pl.charmas.android.reactivelocation.observables.location.LocationUpdatesObservable$1@317862016 (0x12f23080)
|   locationRequest = com.google.android.gms.location.LocationRequest@321623104 (0x132b9440)
|   ctx = com.company.app.register.RegisterActivity@322228768 (0x1334d220)
|   services = java.util.Arrays$ArrayList@321463520 (0x132924e0)
|   shadow$_klass_ = pl.charmas.android.reactivelocation.observables.location.LocationUpdatesObservable
|   shadow$_monitor_ = 0
* Instance of com.company.app.register.RegisterActivity
|   static PERMISSION_ACCESS_FINE_LOCATION = 123
|   static serialVersionUID = 0
|   static $staticOverhead = byte[32]@314826753 (0x12c3e001)
|   static TAG = java.lang.String@315205952 (0x12c9a940)
|   static $change = null
|   confirmEmail = android.support.design.widget.TextInputEditText@314684416 (0x12c1b400)
|   confirmEmailInputLayout = android.support.design.widget.TextInputLayout@314682368 (0x12c1ac00)
|   confirmPassword = android.support.design.widget.TextInputEditText@319913984 (0x13118000)
|   email = android.support.design.widget.TextInputEditText@314681344 (0x12c1a800)
|   password = android.support.design.widget.TextInputEditText@319910912 (0x13117400)
|   registerPhotoImageView = android.support.v7.widget.AppCompatImageView@320738304 (0x131e1400)
|   registerPlusIconImageView = android.support.v7.widget.AppCompatImageView@320738816 (0x131e1600)
|   registerPresenter = com.company.app.register.RegisterPresenter@314815120 (0x12c3b290)
|   validateButton = android.support.v7.widget.AppCompatButton@319944704 (0x1311f800)
|   footerFeatureNameTextView = null
|   presenter = com.company.app.register.RegisterPresenter@314815120 (0x12c3b290)
|   lifecycleSubject = rx.subjects.BehaviorSubject@315648512 (0x12d06a00)
|   mDelegate = android.support.v7.app.AppCompatDelegateImplV23@315108704 (0x12c82d60)
|   mEatKeyUpEvent = false
|   mResources = null
|   mThemeId = 2131361851
|   mCreated = true
|   mFragments = android.support.v4.app.FragmentController@316000960 (0x12d5cac0)
|   mHandler = android.support.v4.app.FragmentActivity$1@315648480 (0x12d069e0)
|   mMediaController = null
|   mNextCandidateRequestIndex = 0
|   mOptionsMenuInvalidated = false
|   mPendingFragmentActivityResults = android.support.v4.util.SparseArrayCompat@315649376 (0x12d06d60)
|   mReallyStopped = true
|   mRequestedPermissionsFromFragment = false
|   mResumed = false
|   mRetaining = false
|   mStopped = true
|   mStartedActivityFromFragment = false
|   mStartedIntentSenderFromFragment = false
|   mActionBar = null
|   mActionModeTypeStarting = 0
|   mActivityInfo = android.content.pm.ActivityInfo@314695936 (0x12c1e100)
|   mActivityTransitionState = android.app.ActivityTransitionState@316275584 (0x12d9fb80)
|   mApplication = com.company.app.SomeAppApplication@319806976 (0x130fde00)
|   mCalled = true
|   mChangeCanvasToTranslucent = false
|   mChangingConfigurations = false
|   mComponent = android.content.ComponentName@316002416 (0x12d5d070)
|   mConfigChangeFlags = 0
|   mCurrentConfig = android.content.res.Configuration@315397696 (0x12cc9640)
|   mDecor = null
|   mDefaultKeyMode = 0
|   mDefaultKeySsb = null
|   mDestroyed = true
|   mDoReportFullyDrawn = false
|   mEmbeddedID = null
|   mEnableDefaultActionBarUp = false
|   mEnterTransitionListener = android.app.SharedElementCallback$1@1899480576 (0x7137c600)
|   mExitTransitionListener = android.app.SharedElementCallback$1@1899480576 (0x7137c600)
|   mFinished = true
|   mFragments = android.app.FragmentController@316000768 (0x12d5ca00)
|   mHandler = android.os.Handler@315648384 (0x12d06980)
|   mHasCurrentPermissionsRequest = false
|   mIdent = 25521734
|   mInstanceTracker = android.os.StrictMode$InstanceTracker@316000832 (0x12d5ca40)
|   mInstrumentation = android.app.Instrumentation@316288384 (0x12da2d80)
|   mIntent = android.content.Intent@315801664 (0x12d2c040)
|   mLastNonConfigurationInstances = null
|   mMainThread = android.app.ActivityThread@316251584 (0x12d99dc0)
|   mManagedCursors = java.util.ArrayList@315648416 (0x12d069a0)
|   mManagedDialogs = null
|   mMenuInflater = null
|   mParent = null
|   mReferrer = java.lang.String@315928768 (0x12d4b0c0)
|   mResultCode = 0
|   mResultData = null
|   mResumed = false
|   mSearchEvent = null
|   mSearchManager = null
|   mStartedActivity = false
|   mStopped = true
|   mTemporaryPause = false
|   mTitle = java.lang.String@321143744 (0x132443c0)
|   mTitleColor = 0
|   mTitleReady = true
|   mToken = android.os.BinderProxy@315453504 (0x12cd7040)
|   mTranslucentCallback = null
|   mUiThread = java.lang.Thread@1961153184 (0x74e4d2a0)
|   mVisibleBehind = false
|   mVisibleFromClient = true
|   mVisibleFromServer = true
|   mVoiceInteractor = null
|   mWindow = com.android.internal.policy.PhoneWindow@322307488 (0x133605a0)
|   mWindowAdded = true
|   mWindowManager = android.view.WindowManagerImpl@315648960 (0x12d06bc0)
|   mInflater = com.android.internal.policy.PhoneLayoutInflater@315206624 (0x12c9abe0)
|   mOverrideConfiguration = null
|   mResources = android.content.res.Resources@316288144 (0x12da2c90)
|   mTheme = android.content.res.Resources$Theme@315648992 (0x12d06be0)
|   mThemeResource = 2131361851
|   mBase = android.app.ContextImpl@314694272 (0x12c1da80)
|   shadow$_klass_ = com.company.app.register.RegisterActivity
|   shadow$_monitor_ = 1252084325
* Excluded Refs:
| Field: android.view.inputmethod.InputMethodManager.mNextServedView
| Field: android.view.inputmethod.InputMethodManager.mServedView
| Field: android.view.inputmethod.InputMethodManager.mServedInputConnection
| Field: android.view.inputmethod.InputMethodManager.mCurRootView
| Field: android.os.UserManager.mContext
| Field: android.net.ConnectivityManager.sInstance
| Field: android.view.Choreographer$FrameDisplayEventReceiver.mMessageQueue (always)
| Thread:FinalizerWatchdogDaemon (always)
| Thread:main (always)
| Thread:LeakCanary-Heap-Dump (always)
| Class:java.lang.ref.WeakReference (always)
| Class:java.lang.ref.SoftReference (always)
| Class:java.lang.ref.PhantomReference (always)
| Class:java.lang.ref.Finalizer (always)
| Class:java.lang.ref.FinalizerReference (always)

**Comment by patloew** [comment]
The leak is from `pl.charmas.android.reactivelocation.observables.location.LocationUpdatesObservable`, which is another library ([Android-ReactiveLocation](https://github.com/mcharmas/Android-ReactiveLocation)). Please create an issue there.

**Comment by carlemil** [comment]
Sorry about that, had several Rx location lib tabs open at the same time and got the wrong one :(
