### ISSUE TITLE
feature request: fallback to android framework location apis when play services unavailable

### ISSUE THREAD

**Issue by kaushikgopal** [patloew/RxLocation#36]
for those unfortunate few, where google play services is unavailable, might make sense to fall back to the native android framework location apis?

**Comment by patloew** [comment]
This library is a wrapper around the play services location APIs, support for the native location APIs is not planned.

**Comment by kaushikgopal** [comment]
makes sense. would you be open to exploring this if you got a PR, or do you want to keep this library focused on play services only?
