### ISSUE TITLE
Attribute application@label value=(...) from AndroidManifest.xml:12:9-35 	is also present at [com.patloew.rxlocation:rxlocation:1.0.3] AndroidManifest.xml:11:18-50 value=(@string/app_name).

### ISSUE THREAD

**Issue by davidbilik** [patloew/RxLocation#38]
Hello, library specifies some application attributes(like label) that shouldnt be there. It fails when merging manifests with error as in title

**Comment by alouanemed** [comment]
did you try adding` tools:replace="android:label"`  to your manifest file ?

**Comment by davidbilik** [comment]
Yes, I know how to solve that but the problem shouldn't be there at the first place :)

**Comment by alouanemed** [comment]
Agree !

**Comment by josh-burton** [comment]
Would be great if this was removed.

**Comment by patloew** [comment]
Fixed in v1.0.5.
