### ISSUE TITLE
Question: How use checkAndHandleResolution to handle only Location

### ISSUE THREAD

**Issue by esdrasdl** [patloew/RxLocation#4]
Hi. I liked you sample about how to use this awesome library. I'm quite new on reactive programming, could you provide a sample on how to use checkAndHandleResolution to recovery only the Location and not an Address? You can see my attempt above. Actually I'm having some trouble to `mRxLocation.location().lastLocation()` returns a Observable < Location > . Am I on the right path?

```
@Override
    public void startLocationPooling() {
        disposable.add(
                mRxLocation.settings().checkAndHandleResolution(locationRequest)
                        .flatMapObservable(this::getLocationObservable)
                        .observeOn(AndroidSchedulers.mainThread())
                        .subscribe(mView::onLocationUpdate, throwable -> Log.e(TAG, "Error fetching location", throwable));
    }

    private Observable<Location> getLocationObservable(boolean success) {
        if (success) {
            return mRxLocation.location().updates(locationRequest);
        } else {
            mView.onLocationSettingsUnsuccessful();
            return mRxLocation.location().lastLocation();
        }
    }
```

**Comment by patloew** [comment]
You are on the right path. `lastLocation()` returns a `Maybe<Location>`. [Maybe](http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/Maybe.html) is a reactive type that either gets you one element (`onSuccess`), no element (`onComplete`) or an error (`onError`). You can convert it to an `Observable` via [`toObservable()`](http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/Maybe.html#toObservable%28%29).

```
private Observable<Location> getLocationObservable(boolean success) {
    if (success) {
        return mRxLocation.location().updates(locationRequest);
    } else {
        mView.onLocationSettingsUnsuccessful();
        return mRxLocation.location().lastLocation().toObservable();
    }
}
```
