### ISSUE TITLE
Switch to Location APIs instead of GoogleApiClient

### ISSUE THREAD

**Issue by optisamit** [patloew/RxLocation#41]
This is kind of an official recommendation from Google: https://android-developers.googleblog.com/2017/06/reduce-friction-with-new-location-apis.html

**Comment by patloew** [comment]
The GoogleApiClient APIs are not deprecated and are actually a better fit for a Rx-library in my opinion. With this library, you manage the lifecycle of the GoogleApiClient via the Rx-Disposable, meaning the whole management of the GoogleApiClient is completely hidden from the user. The new APIs are a good fit for traditional, non-rxified, usage of the Location services though.
