### ISSUE TITLE
setDefaultTimeout is not working

### ISSUE THREAD

**Issue by iam1492** [patloew/RxLocation#44]
for me setDefaultTimeout is not working.
I test with my phone on basement where gps is not working.
I hope time out trigger onError after sometimes but there was no response at all.

**Comment by patloew** [comment]
From the readme: 
> Keep in mind that these timeouts only apply to calls to the Location API, e.g. when registering a location update listener. As an example, the timeout provided to rxLocation.location().updates(locationRequest, 15, TimeUnit.Seconds) does not mean that you will not receive location updates anymore after 15 seconds. Use setExpirationDuration() on your locationRequest for this use case.

If this still does not do what you want, there is a[ RxJava timeout operator](http://reactivex.io/documentation/operators/timeout.html).

**Comment by TonyTangAndroid** [comment]
Based on the source code in `RxLocation.java`,  timeoutTime has never ever been referenced. I think it is supposed to be referenced in `Geofencing.java` but Geofencing.java is always passing null. Could you please double check out whether there has been some potential issue?

```


public void setDefaultTimeout(long time, @NonNull TimeUnit timeUnit) {
        if (timeUnit != null) {
            timeoutTime = time;
            timeoutUnit = timeUnit;
        } else {
            throw new IllegalArgumentException("timeUnit parameter must not be null");
        }
    }
```
