### ISSUE TITLE
Question: Have you integrated FallbackReverseGeocodeObservable just like mcharmas/Android-ReactiveLocation?

### ISSUE THREAD

**Issue by parveenkumardeeva** [patloew/RxLocation#5]
Hi, your library is awesome. Please integrate the fallback for **java.io.IOException: Service not Available** just like mcharmas library.
I would also like to have place autocomplete suggestions feature in this library.

**Comment by patloew** [comment]
This library is now deprecated and not maintained anymore. Please switch to the [CoLocation library](https://github.com/patloew/CoLocation).
