### ISSUE TITLE
Update activity recognition implementation to use ActivityRecognitionClient

### ISSUE THREAD

**Issue by agramian** [patloew/RxLocation#50]
The [`ActivityRecognitionApi`](https://developers.google.com/android/reference/com/google/android/gms/location/ActivityRecognitionApi) interface is now deprecated.

The recommended implementation is to "Use the connectionless API [`ActivityRecognitionClient`](https://developers.google.com/android/reference/com/google/android/gms/location/ActivityRecognitionClient.html) instead."

I have noticed inconsistent and buggy behavior in using it in the current way through `RxLocation` particularly when using `blockingGet()` to remove updates.

**Comment by patloew** [comment]
This library is now deprecated and not maintained anymore. Please switch to the [CoLocation library](https://github.com/patloew/CoLocation).
