### ISSUE TITLE
Can't create new instance

### ISSUE THREAD

**Issue by catalin-florescu** [patloew/RxLocation#51]
I've got this strange error when i'm trying to create a new instance of `RxLocations`

    java.lang.VerifyError: Verifier rejected class com.patloew.rxlocation.LocationSettings: void 
    com.patloew.rxlocation.LocationSettings.<clinit>() failed to verify: void 
    com.patloew.rxlocation.LocationSettings.<clinit>(): [0x0] Call site #2 bootstrap method argument 1 is 
    not a reference (declaration of 'com.patloew.rxlocation.LocationSettings' appears in 
    /data/app/packageName-kBBIMGGI0OZGIlUQ4l5pjw==/split_lib_dependencies_apk.apk)`

What can i do with it? Clean project/invalidate cache won't help...

**Comment by patloew** [comment]
Strange, never had or heard of this problem. Maybe a clash with another dependency?

**Comment by catalin-florescu** [comment]
I don't know. I also use Room, beside RxJava and Retrofit.

**Comment by patloew** [comment]
Could you provide an example project with the problem so that I can test?

**Comment by catalin-florescu** [comment]
Sorry, i changed with other library... I can upload this project in this stage and you can change with your library. Until now is the only thing i've done.
