### ISSUE TITLE
Runtime Error

### ISSUE THREAD

**Issue by DeevD** [patloew/RxLocation#56]
Error:Supertypes of the following classes cannot be resolved. Please make sure you have the required dependencies in the classpath:
    class com.google.android.gms.location.LocationRequest, unresolved supertypes: com.google.android.gms.common.internal.safeparcel.zza

**Comment by patloew** [comment]
Can you please provide an example project?

**Comment by patloew** [comment]
I'll close the issue for now, if you can provide a sample project where the issue is reproducible, I'll reopen it.
