### ISSUE TITLE
For god sake do the documentation of all functions

### ISSUE THREAD

**Issue by Zulqurnain** [patloew/RxLocation#6]
I am currently struggling for correct and valid documentation for this library , only docs available are for few examples shown in read me , but there are still more to go like :

what does "flush()" do ?  
Difference between ObservableSource<Location> and Observable<Location> ? 
How to gracefully handle if you didn't get location permission?
what is alternate for Observable.empty() in this lib ?

These are just few problems , there are number of others too

**Comment by patloew** [comment]
You can find the documentation for the Location APIs – which are wrapped by this library – at the [Google API reference](https://developers.google.com/android/reference/com/google/android/gms/location/package-summary). When I have some time left, I'll add JavaDocs for all methods, according to these references. Meanwhile, you can just take a look there.

For more information about RxJava in general, please refer to the [RxJava documentation](https://github.com/ReactiveX/RxJava/tree/2.x).

You can do permission handling in multiple ways, but this is not the concern of the library. I suggest you may take a look at the [RxPermissions library](https://github.com/tbruyelle/RxPermissions).
