### ISSUE TITLE
How can i do a network provider location ?

### ISSUE THREAD

**Issue by j2emanue** [patloew/RxLocation#61]
I dont see how i can make your api do network provider. i just need COARSE location not FINE location.  i am using 

setPriority(LocationRequest.PRIORITY_BALANCED_POWER_ACCURACY)

but i'd rather use coarse location or have it as an option, is there no way ?

**Comment by patloew** [comment]
The library does not request any permission, it's up to you to request the permission.

**Comment by j2emanue** [comment]
thats not what i was asking actually. thanks for the reply.  there are 3 types of providers:  passive provider, network provider and gps provider. i am asking if i want a network provided location, how do i do that ?

**Comment by patloew** [comment]
As far as I know this is not possible when using the fused location provider API (which is the only API supported by this library). This API abstracts the providers away and only provides a (simpler) `setPriority(…)` method.

See also [here](https://developers.google.com/android/reference/com/google/android/gms/location/LocationRequest):
> Location requests from applications with ACCESS_COARSE_LOCATION and not ACCESS_FINE_LOCATION will be automatically throttled to a slower interval, and the location object will be obfuscated to only show a coarse level of accuracy.

**Comment by j2emanue** [comment]
Yes. I understand. You can close the incident

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
