### ISSUE TITLE
Using RxLocation in a Service

### ISSUE THREAD

**Issue by maciek252** [patloew/RxLocation#62]
The library is great and I like it very much. However, I've got a problem with using it from a Service, for cases when the GPS position needs to be delivered at all times, whether the app is visible or not. The app context is needed, and I don't know how to get it in a Service. Is there a way of constructing RxLocation object without providing Context? Or maybe it's intentional?

**Comment by patloew** [comment]
`Service` is a `Context`.

**Comment by maciek252** [comment]
Yes, but the call to getApplicationContext() returns null when called in the constructor. It needs to be called like this in the service class:

@Override
    public void onCreate() {
        super.onCreate();
        rxWear = new RxWear(getApplicationContext());
...

**Comment by Polyterative** [comment]
While I was able to run the observable in a service, the events stop as soon as I leave the Activities putting the application `onPause`
I've found no way to continue receiving the location while my app is not in focus.
I think this is related to the fact that the events that we receive always come from the `main` thread
