### ISSUE TITLE
Location not found issue

### ISSUE THREAD

**Issue by AntonisSt** [patloew/RxLocation#63]
Hi, your library is great and it helped me resolve a lot of problems I had. But there is a strange issue I'm facing. In some devices, when users open my app, location cannot be determined but if they open google maps and see the blue dot after that the location can be found in my app too. Since, I can't tell users to do this process cause it's a terrible user experience can you tell me a workaround to fix this issue or maybe track it down and reproduce it in order to fix it in the following version of your library? Thx

**Comment by patloew** [comment]
Use `rxLocation.location().updates(…)` to request live location updates.
