### ISSUE TITLE
Not work in apps with target SDK 28

### ISSUE THREAD

**Issue by 9tilov** [patloew/RxLocation#68]
Sample doesn't work with target SDK 28.

**Comment by patloew** [comment]
The sample does not contain runtime permission code to keep it simple and therefore does not work with higher targetSdkVersions. RxLocation itself does not handle permissions, as also stated in the readme:

> Make sure to have the Location and Activity Recognition permissions from Marshmallow on, if they are needed by your API requests.

You can for example take a look at the RxPermissions library to help with permission requests.
