### ISSUE TITLE
No error event if address not exist

### ISSUE THREAD

**Issue by java1developer** [patloew/RxLocation#70]
use any ocean point for reproduce
`disposable.add(rxLocation.geocoding().fromLocation(location.latitude, location.longitude)`
`                .observeOn(AndroidSchedulers.mainThread())`
`                .subscribeOn(Schedulers.io())`
`                .subscribe(new Consumer<Address>() {`
`                   @Override`
`                    public void accept(Address address) {`
`                        view.onAddressUpdate(address);`
`                    }`
`                }, new Consumer<Throwable>() {`
`                    @Override`
`                    public void accept(Throwable throwable) {                     `
`                        Log.e(TAG, "Error fetching location/address updates", throwable);`
`                    }`
`                }));`

**Comment by patloew** [comment]
This library is now deprecated and not maintained anymore. Please switch to the [CoLocation library](https://github.com/patloew/CoLocation).
