### ISSUE TITLE
Handling the location settings resolution no longer works on Android P

### ISSUE THREAD

**Issue by agramian** [patloew/RxLocation#71]
On Android P, `rxLocation.settings().checkAndHandleResolution(locationRequest)` properly detects that there is an issue with the location request and displays the resolution dialog, however choosing OK does not properly resolve the issue anymore.

The conditional below is resolving to `false`:
https://github.com/patloew/RxLocation/blob/2b1dddac094ae53c08f24cda90a938a9ef36c606/library/src/main/java/com/patloew/rxlocation/SettingsCheckHandleSingleOnSubscribe.java#L57

**Comment by Starksoft** [comment]
Facing the same issue

**Comment by jplipata** [comment]
is this library still being maintained?

**Comment by Anurag--Singh** [comment]
Will there be any update?

**Comment by Mostafayehya** [comment]
:(

**Comment by lectricas** [comment]
not working

**Comment by patloew** [comment]
This library is now deprecated and not maintained anymore. Please switch to the [CoLocation library](https://github.com/patloew/CoLocation).
