### ISSUE TITLE
Jcenter sunset

### ISSUE THREAD

**Issue by minirogue** [patloew/RxLocation#78]
[Jcenter is shutting down](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/). Are there any plans to move this library to Maven Central or somewhere else to support apps that are still using it?

**Comment by patloew** [comment]
I'm currently in the process of moving it to maven central. Will update readme once it's done.

**Comment by patloew** [comment]
The latest version 1.0.5 is now available on Maven Central.
