### ISSUE TITLE
is this library uses BACKGROUND LOCATION ?

### ISSUE THREAD

**Issue by erlangparasu** [patloew/RxLocation#79]
is this library make a request to ACCESS_BACKGROUND_LOCATION?

**Comment by patloew** [comment]
This library does not make any permission requests at all, you have to take care of that before calling any library functions.

**Comment by erlangparasu** [comment]
app got removed from gplay because it access to background location. i need to migrate to another lib with foreground access (using foreground service notification) to access the location.

**Comment by erlangparasu** [comment]
target: android API 29 (Q)
