### ISSUE TITLE
How to deal with GoogleAPIConnectionSuspendedException ?

### ISSUE THREAD

**Issue by josenaves** [patloew/RxLocation#9]
I'm getting the error below: 

11-18 16:52:52.382 3476-3476/com.dispatchr.mobile.workr W/System.err: com.patloew.rxlocation.GoogleAPIConnectionSuspendedException
11-18 16:52:52.382 3476-3476/com.dispatchr.mobile.workr W/System.err:     at com.patloew.rxlocation.BaseFlowable$ApiClientConnectionCallbacks.onConnectionSuspended(BaseFlowable.java:88)
11-18 16:52:52.382 3476-3476/com.dispatchr.mobile.workr W/System.err:     at com.google.android.gms.common.internal.zzk.zzgn(Unknown Source)
11-18 16:52:52.382 3476-3476/com.dispatchr.mobile.workr W/System.err:     at com.google.android.gms.internal.zzrd.zzc(Unknown Source)
11-18 16:52:52.382 3476-3476/com.dispatchr.mobile.workr W/System.err:     at com.google.android.gms.internal.zzra.onConnectionSuspended(Unknown Source)
11-18 16:52:52.382 3476-3476/com.dispatchr.mobile.workr W/System.err:     at com.google.android.gms.internal.zzrf.onConnectionSuspended(Unknown Source)
11-18 16:52:52.382 3476-3476/com.dispatchr.mobile.workr W/System.err:     at com.google.android.gms.internal.zzqr.onConnectionSuspended(Unknown Source)
11-18 16:52:52.382 3476-3476/com.dispatchr.mobile.workr W/System.err:     at com.google.android.gms.common.internal.zzj$1.onConnectionSuspended(Unknown Source)
11-18 16:52:52.382 3476-3476/com.dispatchr.mobile.workr W/System.err:     at com.google.android.gms.common.internal.zze$zzd.handleMessage(Unknown Source)
11-18 16:52:52.382 3476-3476/com.dispatchr.mobile.workr W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
11-18 16:52:52.382 3476-3476/com.dispatchr.mobile.workr W/System.err:     at android.os.Looper.loop(Looper.java:135)
11-18 16:52:52.382 3476-3476/com.dispatchr.mobile.workr W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5376)
11-18 16:52:52.382 3476-3476/com.dispatchr.mobile.workr W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
11-18 16:52:52.382 3476-3476/com.dispatchr.mobile.workr W/System.err:     at java.lang.reflect.Method.invoke(Method.java:372)
11-18 16:52:52.382 3476-3476/com.dispatchr.mobile.workr W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
11-18 16:52:52.382 3476-3476/com.dispatchr.mobile.workr W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)

**Comment by patloew** [comment]
Please take a look at the [GoogleApiClient.ConnectionCallbacks docs](https://developers.google.com/android/reference/com/google/android/gms/common/api/GoogleApiClient.ConnectionCallbacks.html#onConnectionSuspended%28int%29).

**Comment by gingo** [comment]
Its still unclear to me how to handle this exception properly. Shouldn't RxLocation silently wait for next onConnected(Bundle) as mentioned in documentation?
